### ISSUE TITLE
Documentation does not close <%include> tag

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/mako#260]
**Migrated issue, originally created by Javier Ruere ([@jruere](https://github.com/jruere))**

Here: http://docs.makotemplates.org/en/latest/inheritance.html#using-include-with-template-inheritance

**Comment by sqla-tester** [comment]
**Abhilash Raj** has proposed a fix for this issue in the **main** branch:

**Add closing tag in include.** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3777
