### ISSUE TITLE
how to use i18n in Django1.8+Mako 

### ISSUE THREAD

**Issue by lzr1994** [sqlalchemy/mako#284]
I can simply use i18n when i use Django templates. But it became very difficult when I add Mako in my Django project. Mako templates can not be used Django i18n tags.

is code :
{% load i18n %}
{% trans 'hello test' %}
but , this code cant be read by Mako Templates,
so how to Internationalization using Mako+Django , I can't find a valid method
thanks

**Comment by hilarryxu** [comment]
Those are django template features, cannot be directly applied to mako template.

**Comment by zzzeek** [comment]
I think there's nothing to be done here on the Mako side.
