### ISSUE TITLE
%doc tag can not be nested in another %doc tag

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/mako#285]
i discovered this when using `<%doc>` to comment out a chunk of a mako template which contained a `<%doc>foo</%doc>` node.

encountering the nested tag confuses the parser.

this doesn't need to be fixed. i could do a pr for the docs saying "this tag can not be nested", but I figure putting a ticket and "wontfix" here will be good enough for anyone who finds this out in the future.

**Comment by zzzeek** [comment]
right there's no way things like that are changing these days...
