### ISSUE TITLE
Custom template tags and filters support 

### ISSUE THREAD

**Issue by DulceZavaleta** [sqlalchemy/mako#291]
Hello. I'm trying to use this package https://github.com/jazzband/django-widget-tweaks, to add styling to forms. However, I'm not sure how to load these filters in Mako. I found instructions about how to do it with default django templating, https://docs.djangoproject.com/en/2.1/howto/custom-template-tags but it doesn't work with Mako. Anyone knows how to do it? Or you can't?

**Comment by zzzeek** [comment]
hi there -

unfortunately I'm not sure how the filters in that package work, however if you can get a Python callable from them, you would use that callable as your filter:

```


<%!

from django_widget_tweaks import some_python_module

%>

Here's some tagged text: ${"text" | some_python_module.some_filter}
```

docs on this are at https://docs.makotemplates.org/en/latest/filtering.html
