### ISSUE TITLE
inspect.getfullargspec() is deprecated in python 3.8

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/mako#295]
as in https://github.com/sqlalchemy/sqlalchemy/issues/4674

and https://github.com/sqlalchemy/alembic/issues/563

need to rebuild based on Signature for what we need

**Comment by zzzeek** [comment]
we are using getargspec in exactly the prehistoric "turbogears" plugin, and we're using it on our own Template.__init__ which seems kind of silly.  we should just remove it

**Comment by zzzeek** [comment]
bzzt I'm wrong, we should fix the TG thing but we use it in runtime as well via inspect_func_args

**Comment by zzzeek** [comment]
getargspec is used in Mako for

- TG thing which we can remove

- kwargs_for_callable and kwargs_for_include which are template callables generated by mako

**Comment by zzzeek** [comment]
here is the turbogears part:

```
diff --git a/mako/ext/turbogears.py b/mako/ext/turbogears.py
index eaa2d78..8e0394d 100644
--- a/mako/ext/turbogears.py
+++ b/mako/ext/turbogears.py
@@ -29,9 +29,9 @@ class TGPlugin(object):
         self.lookup = TemplateLookup(**lookup_options)
 
         self.tmpl_options = {}
-        # transfer lookup args to template args, based on those available
-        # in getargspec
-        for kw in compat.inspect_getargspec(Template.__init__)[0]:
+        # transfer lookup args to template args, based on those which
+        # the TemplateLookup would use
+        for kw in self.lookup.template_args:
             if kw in lookup_options:
                 self.tmpl_options[kw] = lookup_options[kw]

```

but the rest has to be from a new approach to getfullargspec

**Comment by zzzeek** [comment]
this needs to be vendored the same way we did it at https://github.com/sqlalchemy/sqlalchemy/issues/4674, cut and paste

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Bump Python versions, remove conditional imports** https://gerrit.sqlalchemy.org/1380
