### ISSUE TITLE
Impossible(?) to render a template that is already JSP.

### ISSUE THREAD

**Issue by mcampbell** [sqlalchemy/mako#309]
I have a JSP that I want rendered by Mako, but it seems impossible.  The simplest case is this:

`Template('<%@ taglib uri="foo" prefix="bar" %>').render()`  cannot be made to work, as far as I can tell.  indeed, simply:

`Template('<%').render()` cannot be made to output `<%` in any form I've been able to figure out.

Is this possible?

**Comment by zzzeek** [comment]
Here are code examples illustrating a series of techniques, there are likely more ways to do this depending on your needs:
```

from mako.template import Template

# method one: literal
t = Template("${'<%'}")

print(t.render())


# method two: use a preprocessor (this can be used to automate any approach)
def escape_percents(txt):
    # this can be more intelligent to look for
    # JSP-specific patterns, etc.
    return txt.replace('%', '${"%"}')

t = Template('<%', preprocessor=escape_percents)

print(t.render())


# method three: use <%text>
t = Template("""<%text>
<% some jsp code  %>
</%text>""")

print(t.render())
```

**Comment by mcampbell** [comment]
I will investigate these; thanks.
