### ISSUE TITLE
%% not working when not at the beginning of the line

### ISSUE THREAD

**Issue by pjadzinsky** [sqlalchemy/mako#323]
Hello,

Thanks for developing and maintaining a great package. 

I have a template that looks like this
```
# -*- coding: utf-8 -*-
%%pip install package
if <some condition>:
    %%pip install <some other package>
```

This gets rendered into 
```
# -*- coding: utf-8 -*-
%pip install package
if <some condition>:
    %%pip install <some other package>
```

where the last line starts with (some spaces) + %%

Trying to template
```
# -*- coding: utf-8 -*-
%%pip install package
if <some condition>:
    %pip install <some other package>
```

Raises
Thanks again

**Comment by zzzeek** [comment]
hi 

these must be escaped as mentioned at https://docs.makotemplates.org/en/latest/syntax.html#control-structures

so in this case you'd want %%%

**Comment by zzzeek** [comment]
I don't know what's up with the second one, might be a bug, but Mako is not maintained right now (unless someone wants to wriet a PR w/ tests).

try a literal block
```

t = Template("""
# -*- coding: utf-8 -*-
%%%pip install package
if <some condition>:
    ${"%"}pip install <some other package>

""")

```

**Comment by pjadzinsky** [comment]
Thanks for the reply

**Comment by sqla-tester** [comment]
**Hai Zhu** has proposed a fix for this issue in the **main** branch:

**fix percent escape not working when not at the beginning of the line** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5111

**Comment by zzzeek** [comment]
I've reverted in edf44dc36ef2ed42746352 and revoked 1.3.1.  This issue remains un-fixed

**Comment by sqla-tester** [comment]
**Hai Zhu** has proposed a fix for this issue in the **main** branch:

**fix percent escape not working when not at the beginning of the line** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5141

**Comment by zzzeek** [comment]
1.3.2 is released thanks again, will revisit here if further problems
