### ISSUE TITLE
Prepare 1.2

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/mako#340]
- [x] modernize setup: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3078
- [x] drop py2: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3078
- [x] github workflow: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3078
- [x] improve code: see https://github.com/sqlalchemy/mako/pull/335
- [x] update black : redo https://github.com/sqlalchemy/mako/pull/312
- [x] remove pkg_resource usage #347 
- [x] #351 
- [x] #352

**Comment by jvanasco** [comment]
For the "update black" item, I suggest re-doing PR #312, which standardizes the black integration into the same config as other sqlalchemy projects:

* migrate black config to pyproject.toml
* update black version

If you have time, I would also copy/paste this:

* update README to showcase code-of-conduct and development links

**Comment by bourke** [comment]
Adding this:

- [ ] #351

**Comment by bourke** [comment]
Implemented in [c8140243](https://github.com/sqlalchemy/mako/commit/c81402434e8a277b0134262ad485debcffa20280)
