### ISSUE TITLE
Refactor test suite and utilities to be more self-contained and better-behaved under Python 3

### ISSUE THREAD

**Issue by bourke** [sqlalchemy/mako#348]
The test suite has a number of structural issues, e.g. including functionality in the package ``__init__.py``, as well as implicit relative imports left over from Python 2.

**Comment by sqla-tester** [comment]
**Ram Rachum** has proposed a fix for this issue in the **main** branch:

**Fix exception causes in lookup.py** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3337
