### ISSUE TITLE
sweep for py2k install directives, such as 'wheel=universal'

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/mako#351]
see https://github.com/sqlalchemy/alembic/issues/893 for a similar issue in Alembic where 'wheel=universal' creates wheels targeted by py2 when people use pip.  mako still has this.    we should do a sweep to make sure the world of python 2 installers have zero chance of installing mako 1.2

**Comment by sqla-tester** [comment]
**Michael Bourke** has proposed a fix for this issue in the **main** branch:

**Corrected universal wheel directive; building wheels now targets Python 3 only** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3437
