### ISSUE TITLE
Remove remaining Python 2 residue

### ISSUE THREAD

**Issue by bourke** [sqlalchemy/mako#352]
Some Unicode literals, etc., are still hanging around in the codebase and should be removed before releasing 1.2.

**Comment by sqla-tester** [comment]
**Michael Bourke** has proposed a fix for this issue in the **main** branch:

**Remove Python 2 residue; use Python 3 idioms** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3435
