### ISSUE TITLE
pip3 install of mako-1.2.1 fails

### ISSUE THREAD

**Issue by bdubbs** [sqlalchemy/mako#363]
At linuxfromscratch we are trying to convert to the python recommended use of pip3 to install modules.  What we are doing is downloading the module source and after untarring:

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
(as root) pip3 install --no-index --find-links dist --no-cache-dir Mako

This worked fine for mak0-1.2.0.  For make-1.2.1, creating the wheel works, but installing does not:

Making Mako-1.2.1
Fri Jul  1 02:18:14 PM CDT 2022
Processing /build/mako/Mako-1.2.1
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: Mako
  Building wheel for Mako (pyproject.toml): started
  Building wheel for Mako (pyproject.toml): finished with status 'done'
  Created wheel for Mako: filename=Mako-1.2.1-py3-none-any.whl size=78629 sha256=271ea0d8835a00de1d02e787ef89c86eb22a8c802b599bdbd9593e9c7a48ca7e
  Stored in directory: /home/bdubbs/.cache/pip/wheels/f9/60/1f/a506fe41b85daa187fb3d7e5002dab98bc750145d7f81825e8
Successfully built Mako
Looking in links: dist
Processing ./dist/Mako-1.2.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement MarkupSafe>=0.9.2 (from mako) (from versions: none)
ERROR: No matching distribution found for MarkupSafe>=0.9.2

However MarkupSafe-2.1.0 is installed.  Using the above pip3 commands works (and still works) for Mako-1.2.0.

The old method if installing Mako using "python3 setup.py install --optimize=1" does continue to work.

**Comment by zzzeek** [comment]
hi  -

I would ensure you have upgraded pip to the latest version and if further problems report this to https://github.com/pypa/pip, nothing has changed from mako 1.2.0 to 1.2.1 regarding setup or requirements. 

1.2.1:

```
$ pip install mako
Collecting mako
  Downloading Mako-1.2.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 3.6 MB/s eta 0:00:00
Collecting MarkupSafe>=0.9.2
  Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: MarkupSafe, mako
Successfully installed MarkupSafe-2.1.1 mako-1.2.1
(.venv) [classic@photon3 foo]$ pip3 install mako
Requirement already satisfied: mako in ./.venv/lib/python3.10/site-packages (1.2.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.venv/lib/python3.10/site-packages (from mako) (2.1.1)
```

**Comment by bdubbs** [comment]
My fault.  pip3 usage error. Closing.
