### ISSUE TITLE
quoted sections in tag not grouped correctly

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/mako#366]
this will crash the Lexer due to the regex:

```py
from mako.lexer import Lexer
template = "<%0" + '"' * 3000
Lexer(template).parse
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix tag regexp to match quoted groups correctly** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4053
