### ISSUE TITLE
second lexer reg memory use issue

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/mako#367]
```py
>>> from mako.lexer import Lexer
>>> template = '<%def name="foo()"> this is a def. </%' + ' ' * 10000
>>> Lexer(template).parse()
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**replace "dot" with "set not containing whitespace"** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/4091
