### ISSUE TITLE
Mako 1.3.0 release

### ISSUE THREAD

**Issue by Jamim** [sqlalchemy/mako#380]
Hello @zzzeek,

🙇🏻‍♂️ First of all, thank you for your work on this great project!

Today it's been almost a year since `Mako 1.2.4` was released.
I noticed `1.3.0` is supposed to introduce explicit support for `Python 3.12` which is an anticipated change in my case. I understand that besides this there are not so many changes, but I still believe it's worth releasing anyway.

It would be great if we have any timeline for a new release. In case there are some blockers or pending issues which should be resolved before the release, it would be nice to have some list of them, so those who interested might participate in solving.

Best regards!

**Comment by zzzeek** [comment]
oh, looks like I forgot to release.  moment

**Comment by zzzeek** [comment]
that's out now good luck

**Comment by Jamim** [comment]
Thank you so much!
