### ISSUE TITLE
Wrong HTML meta tag in docs from release tarball

### ISSUE THREAD

**Issue by xry111** [sqlalchemy/mako#385]
In Mako-1.3.2 release tarball, the HTML docs contains a wrong meta tag:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

(lacking a `/` before `>`).

**Comment by zzzeek** [comment]
hi....did that *appear* in 1.3.2 or it's been there all along?

**Comment by xry111** [comment]
Also 1.3.1.  I've not checked earlier releases...

**Comment by zzzeek** [comment]
OK.  it's been there awhile, here it is in SQLAlchemy's docs on the site also: view-source:https://docs.sqlalchemy.org/en/20/

so this is part of https://github.com/sqlalchemyorg/zzzeeksphinx/

**Comment by zzzeek** [comment]
https://github.com/sqlalchemyorg/zzzeeksphinx/issues/22
