### ISSUE TITLE
how do you pass a dict as a parameter to <%namespace:def

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/mako#400]
### Discussed in https://github.com/sqlalchemy/mako/discussions/396

<div type='discussions-op-text'>

<sup>Originally posted by **jjgalvez** May  5, 2024</sup>
How do I pass a dict to a def when it's called from <%namespace:def>.
I would expect that calling 
```<%namespace:def param="${ {'id':123} }"></namespace:def>``` to work, but when I do I get an error saying I am missing a closing ```}```
for reference ```<%call expr="namespace.def(param={'id':123})"></%call>``` works as expected.
</div>

**Comment by sqla-tester** [comment]
**Jose** has proposed a fix for this issue in the **main** branch:

**Update parsetree.py removed "?" from for x in re.compile(r"(\${.+})" …** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5296

**Comment by zzzeek** [comment]
bug remains open as we have to revert this, see #401

**Comment by sqla-tester** [comment]
**Hai Zhu** has proposed a fix for this issue in the **main** branch:

**Support the direct passing of dictionary literals.** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5558
