### ISSUE TITLE
Keyword only arguments after bare `*` are not enforced because of rewrite.

### ISSUE THREAD

**Issue by ianjosephwilson** [sqlalchemy/mako#405]
I guess technically this is a bug but seems pretty insignificant especially since it has been 10 years since the last seemingly related commit.

This should produce a TypeError but seems to not to by accident because the bare `*` is rewritten out:

```mako
<%def name="kwonly(a, *, b=15)">
a=${a} b=${b}
</%def>

${kwonly(1, 2)}
```

**Comment by sqla-tester** [comment]
**Ian Wilson** has proposed a fix for this issue in the **main** branch:

**Document / test quirk that kw only args can be passed positionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5337

**Comment by zzzeek** [comment]
thanks!
