### ISSUE TITLE
Undocumented <& sequence

### ISSUE THREAD

**Issue by joelspadin** [sqlalchemy/mako#412]
I am using Mako to generate some Devicetree code, and I was surprised to find that
```dts
property = <&node>;
```
gets turned into
```dts
property = &node>;
```
when run through Mako. 

I cannot find anything on https://docs.makotemplates.org/en/latest/ that documents `<&` (less than, ampersand) as a special sequence, but I do see it in a couple example files in this repo. Is this a feature that should be documented?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont consume ampersands** https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5561

**Comment by zzzeek** [comment]
from all indications this appears to be an erroneous character that was committed to mako 17 years ago as part of its original construction.  I can find no use for this ampersand character.  seems a little strange

**Comment by joelspadin** [comment]
Weird. Thanks for looking into it!

**Comment by zzzeek** [comment]
looks like it's from myghty since as you mention it's in the example files, it's in the myt files

**Comment by zzzeek** [comment]
ive released 1.3.6, however if this causes any regressions we might have to revert it, as that's been a thing lately

**Comment by joelspadin** [comment]
Thanks!

**Comment by git-bruh** [comment]
Hey, this seems to break firefox builds as a lot of their autogenerated code seems to rely on this quirk: https://github.com/mozilla/gecko-dev/blob/3b1f061102e8137e49c76382170045d9451e4406/servo/components/style/properties/properties.mako.rs#L8

This isn't a problem for now as firefox's build system use an older, bundled mako version. I faced this as I was forcing it to use my system's mako package which is newer than the bundled version.

**Comment by zzzeek** [comment]
firefox browser uses mako in their build system?   unbelievable

anyway firefox should fix their templates when they upgrade, this was a real bug
